services:

  # Backend (Spring Boot)
  - type: web
    name: smartthink-backend
    env: docker
    plan: free
    region: ohio
    rootDir: backend
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

  # Frontend (React + Vite)
  - type: web
    name: smartthink-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: smartthink-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
